# Generated by Django 3.1.7 on 2021-03-14 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210314_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_post',
        ),
        migrations.AddField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
